### ISSUE TITLE
[Suggestion/v2] Allow the ability to explicitly specify true/false or on/off for decorations

### ISSUE THREAD

**Issue by RodneyMKay** [Vankka/EnhancedLegacyText#1]
Thanks for publishing this library. I love using it ^^
I saw you were working on a v2 and I wanted to share a thought I had while reading through the new spec. I hope this is the right place to do it.

When using a decoration applied to a text, the current (with current, I'm referring to V2 here) syntax is that you specify ``[decoration:bold]`` and then specify the same tag at the end to signal the end of that decoration. Having the closing tag match the beginning tag has the disadvantage that when you specify one too many or one to few tags in your message, the entire formatting of the message changes and not just up to the closing tag. 

My proposal would be to add additional optional syntax to deocrations to specify if they're meant to be on or off. This could look something like ``[bold:true]`` or ``[bold:on]`` for the beginning and ``[bold:false]`` (or ``[bold:off]`` respectively) for the ending tag.

Sidenote:
I like that inclusion of the decoration prefix inside of the brackets is optional (and I personally could see removing it entirely), since in my opinion having the top-level keyword (click, hover, color, bold, etc.) be the same keyword as the end keyword is a nice mental model. That way there's visual consistency between the following examples:
- ``[color:red]foo[color]``
- ``[bold:on]foo[bold]``
- ``[strikethough:on]foo[strikethrough]``
- ``[click:open_url:https://example.com/]foo[click]``
- ``[hover:show_text:bar]foo[hover]``

If you have any questions, feel free to hit me up on Discord: ``Rodney#1203``

**Comment by Vankka** [comment]
Thanks for the feedback! 

I do like the idea of specifying on/off/true/false for styles instead of just toggling.

Perhaps to keep decorations consistent with the other tags,
- tags would have the second "parameter" of on/off/true/false (as you described)
  - tags without that parameter would only disable the decoration

Also I do agree that `decoration:` could be removed, it is pretty long

In this case:
- decoration tags can be enabled with:
  - `[bold:true]` / `[bold:on]`
- decoration tags can be disabled with:
  - `[bold:false]` / `[bold:off]`
  - `[bold]`

**Comment by Vankka** [comment]
I went ahead and implemented what I described and updated the wiki

**Comment by RodneyMKay** [comment]
Oh wow, that was quick. I was about to respond that it looks good :p
